name: Update Version Number

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  update-version:
    runs-on: windows-latest

    steps:
  
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Update Version Number   
          shell: bash
          run: |
            # Assuming your version is in the format "Version: X.X"
            export LC_ALL=en_US.UTF-8 
            apt-get update
            apt-get install -y bc
            CURRENT_VERSION=$(grep -oP 'Version: \K\d+\.\d+' app.js)
            NEW_VERSION=$(echo "$CURRENT_VERSION + 0.01" | bc)
            sed -i "s/Version: $CURRENT_VERSION/Version: $NEW_VERSION/" app.js

